### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by themadmrj** [sbis04/video_trimmer#108]
First of, thanks for making the library, it's an excellent base for most devs who need a quick solution.

After having implemented it, I noticed several design issues:
-why separate the Trimmer() instance from the TrimmingView()? The screen should contain the instance and simply return the new file
-global variables are a bad pattern, I think the player should be passed along
-changing the start or end is sometimes very, very slow and will cause skipping frames. This is actually not required, since the user is only interested in the end result, meaning the start/end changes should only be applied once, when the dragging motion stops.
-when the total video duration is greater than the max duration set, moving that duration is near impossible. [This solution](https://github.com/huangred/video_trimmer) is mandatory

I'll write a PR which will adress those issues.

**Comment by themadmrj** [comment]
PR is up. Also solves #43. The solution for #43 I linked had horrible design, so I wrote a cleaner, simpler system myself.
@Everyone for future reference: I plan on creating my own plugin for trimming videos in around 2 months or so, this time using native ressources. Ffmpeg is just too big for a mobile app.

**Comment by sbis04** [comment]
Fixed in PR #109
