### ISSUE TITLE
Remove unused dependency

### ISSUE THREAD

**Issue by themadmrj** [sbis04/video_trimmer#113]
`file_picker: ^3.0.2+2`, there in the main lib when only used in the example. On iOS, this caused me a world of trouble, because file_picker uses `SDWebImage` instead of `SDWebImage/Core`, which prevented me from archiving my app due to multiple targets issue.

**Comment by sbis04** [comment]
I have removed the unused dependency in the latest version (`video_trimmer: ^0.5.2`)
