### ISSUE TITLE
Slidable implementation of the TrimEditor

### ISSUE THREAD

**Issue by lan2000** [sbis04/video_trimmer#114]
video_trimmer 0.5.1
android 10

TrimEditor's sliding selection time period is abnormal.
No such problem in the previous version.

**Comment by lan2000** [comment]
When the video thumbnail is loaded, the white selection box control cannot slide

https://user-images.githubusercontent.com/29618907/123928344-68cac700-d9c0-11eb-8251-3763a35269fd.mp4

**Comment by sbis04** [comment]
@lan2000 have you set any `maxVideoLength` while using the `TrimEditor` widget?

Can you please share the code snippet of just the `TrimEditor` widget, so that I would get to know how you have declared it?

Also, please attach your Flutter doctor output.

**Comment by lan2000** [comment]
flutter doctor
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (4 available)

• No issues found!

The above problem occurs when I set  viewerWidth   beyond the screen width

```
TrimEditor(
                      trimmer: _trimmer,
                      viewerHeight: 50.0,
                      // viewerWidth: MediaQuery.of(context).size.width,
                      viewerWidth: 3000,
                      maxVideoLength: Duration(seconds: 5),
                      onChangeStart: (value) {
                        _startValue = value;
                      },
                      onChangeEnd: (value) {
                        _endValue = value;
                      },
                      onChangePlaybackState: (value) {
                        setState(() {
                          _isPlaying = value;
                        });
                      },
                    )
```

**Comment by lan2000** [comment]
Another problem is that if the video duration is relatively long, the distance selected by TrimEditor becomes shorter and it is difficult to slide. The video just selected is about 4 minutes. The slider on the right side of TrimEditor can't slide.

https://user-images.githubusercontent.com/29618907/124064461-696a6880-da67-11eb-96fe-764296e5d9c9.mp4

**Comment by sbis04** [comment]
> The above problem occurs when I set viewerWidth beyond the screen width

Yes, if you set the `viewerWidth` to be greater than the screen width this would occur because currently the thumbnails are generated in a is scrollable `ListView`.

> Another problem is that if the video duration is relatively long, the distance selected by TrimEditor becomes shorter and it is difficult to slide.

Yes, this is also an issue. I'll try to work on a fix for these soon.

**Comment by harsuu942** [comment]
Any solutions for new version 1.0.0?
