### ISSUE TITLE
fatal error: 'mobileffmpeg/LogDelegate.h' file not found

### ISSUE THREAD

**Issue by wangyan-png** [sbis04/video_trimmer#117]
video_trimmer：0.3.4
I can compile and run normally, but flutter build IOS reports an error
fatal error: 'mobileffmpeg/LogDelegate.h' file not found
'mobileffmpeg/ExecuteDelegate.h' file not found

**Comment by Arjunraj-k** [comment]
Have the same issue as well. anyone got any solutions?

**Comment by sbis04** [comment]
@wangyan-png can you please try with the latest version of the `video_trimmer`, also please share your `flutter doctor` output here.

Also, you can check out this thread on `flutter-ffmpeg`: https://github.com/tanersener/flutter-ffmpeg/issues/303

**Comment by fauzipadlaw** [comment]
Encountering the same issue.

```
› flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.5.0-2.0.pre.113, on macOS 11.5 20G71 darwin-arm,
    locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

and using `video_trimmer: ^0.5.4`

**Comment by dilbersha** [comment]
any updates?

**Comment by masfour7** [comment]
Any updates?!

**Comment by sbis04** [comment]
[flutter-ffmpeg](https://github.com/tanersener/flutter-ffmpeg) plugin is currently archived, I'll update this package to use the newer implementation ([ffmpeg_kit_flutter](https://pub.dev/packages/ffmpeg_kit_flutter)) by next week.

**Comment by masfour7** [comment]
Great; it's been taking me hours to solve the problem but nothing did! Hopefully that solves it. Thanks and your package is great by the way!

**Comment by sbis04** [comment]
I have updated the package with the `ffmpeg_kit_flutter` migration. Try the latest version of this package (`1.0.0`) and let me know if it fixes the issue.

**Comment by Mumtaz12** [comment]
its work for me  by adding this in  pods file 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
