### ISSUE TITLE
TrimEditor widget doesn't work correctly

### ISSUE THREAD

**Issue by tridianthor** [sbis04/video_trimmer#118]
Hi. 
I'm using the latest version 0.5.2.
And the TrimEditor widget doesn't show the slider, it only shows the white circle.
Built on Samsung S8+ - Android 9, Android Studio emu - Android 8, produced the same result.

![Screenshot_20210702-170923(2)](https://user-images.githubusercontent.com/79877056/124264176-5b4b4380-db5e-11eb-9aeb-64507f03294e.jpg)

**Comment by dannycortesv** [comment]
Also having this issue, have you managed to solve it?

**Comment by sbis04** [comment]
This maybe a video specific problem, can you please share the link or the video file here, so that I can test it out with that?

Some information regarding this error is [here](https://github.com/sbis04/video_trimmer/pull/115#issuecomment-872030325).

**Comment by tridianthor** [comment]
> 
> 
> Also having this issue, have you managed to solve it?

Hey, I managed to fix the issue.
before I upgrade to 0.5.2, I used the forked version from https://github.com/huangred/video_trimmer 
and I had initialized the var _startValue = 0 and _endValue = 10
But then after updating and encountering this error, I initialized it to _startValue = 0 and _endValue = 0
And it fixed the problem for me.

**Comment by dannycortesv** [comment]
With 4.0.0 version it works, testing the same video with 0.5.2 version it doesn't work

**Comment by sbis04** [comment]
Hi @dannycortesv, can you share some more details regarding your issue

**Comment by jagritjkh** [comment]
any update on this?
facing the same issue while using v1.*

**Comment by bluejoyq** [comment]
I solved it by adding values of onChangeEnd and onChangeStart and lowering the thumbnail quality.

`TrimEditor(
                  circlePaintColor: Theme.of(context).colorScheme.tertiary,
                  borderPaintColor: Theme.of(context).colorScheme.tertiary,
                  durationTextStyle: Theme.of(context).textTheme.bodyText2!,
                  trimmer: trimmer,
                  maxVideoLength: const Duration(minutes: 2),
                  viewerWidth: MediaQuery.of(context).size.width - 80,
                  thumbnailQuality: 15,
                  onChangeEnd: (value) {},
                  onChangeStart: (value) {},
                ),`

**Comment by NoizyCr1cket** [comment]
Make sure the TrimEditor is built before the Trimmer is initialized. The TrimEditor waits for the Trimmers' initialization event, but it never receives the event if it wasn't built before the Trimmer initialized. For example, I was showing a loading indicator instead of TrimEditor until _after_ the Trimmer initialized. This was causing your same issue for me.

**Comment by sbis04** [comment]
Closing this issue. Please open a new issue if you want to discuss this further.
