### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ankitsaurabhinfosys** [sbis04/video_trimmer#121]
app crashing will saving trimmed video

**Comment by sbis04** [comment]
@ankitsaurabhinfosys can you please share the error logs from the console, and also please attach the `flutter doctor -v` output along with it.

Which version of `video_trimmer` are you using?

**Comment by ankitsaurabhinfosys** [comment]
solved

**Comment by ankitsaurabhinfosys** [comment]
Bad JNI version returned from JNI_OnLoad in....... this was the error. solved moving mavenCentral() in allproject-- repositories

**Comment by sbis04** [comment]
Okay
