### ISSUE TITLE
Trimmer widget issue

### ISSUE THREAD

**Issue by ankitsaurabhinfosys** [sbis04/video_trimmer#122]
In version 0.4.0  VideoViewer(trimmer: _trimmer,), the trimmer parameter is showing "The named parameter 'trimmer' isn't defined."
Cant able to dispose trimmer
![trimmer issue](https://user-images.githubusercontent.com/78646452/127810411-1abb42e9-6c12-490e-8fd1-37dc90aaf5b0.png)

**Comment by zuruoke** [comment]
I think you're using an old version, switch to the 0.5.4 version

**Comment by sbis04** [comment]
@ankitsaurabhinfosys is the issue solved?

**Comment by ankitsaurabhinfosys** [comment]
yes
