### ISSUE TITLE
Bug build release when using ext.flutterFFmpegPackage = 'min-lts' in Android

### ISSUE THREAD

**Issue by duy1998** [sbis04/video_trimmer#129]
![image](https://user-images.githubusercontent.com/43132958/131611890-4ffcfefd-cb1d-4be2-9201-9270547948ef.png)

**Comment by sbis04** [comment]
Please try using the latest version of this package `1.0.0`, there's a breaking change due to the migration of `flutter_ffmpeg` to `ffmpeg_kit_flutter` (more info [here](https://github.com/tanersener/flutter-ffmpeg/issues/345)).
