### ISSUE TITLE
How to get video file that trimmed ? I cant see on my storage 

### ISSUE THREAD

**Issue by DiksDev** [sbis04/video_trimmer#13]
Please suggest me

**Comment by sbis04** [comment]
In order to access the output video file outside the app, use the `storageDir` property in the `saveTrimmedVideo()` method to pass `StorageDir.externalStorageDirectory` for saving it in the external storage.

**Comment by DiksDev** [comment]
Hi....can you write that particular code section Bcz....im not getting

**Comment by DiksDev** [comment]
Thanks......Got it !

**Comment by sbis04** [comment]
Closing this issue as it is fixed.

**Comment by kensou123** [comment]
@DiksDev Hi, sir. Can you give me some example to save the output video file to temporary directory?
