### ISSUE TITLE
Thumbnail issue

### ISSUE THREAD

**Issue by ankitsaurabhinfosys** [sbis04/video_trimmer#132]
Not getting thumbnail after trimming the video, shows Unhandled Exception: Unsupported operation: Functionality only available on Android video trimmer using directory StorageDir.externalStorageDirectory. for ios i have applied StorageDir.applicationDocumentsDirectory but the thumbnail is not getting

**Comment by sbis04** [comment]
This might be related to the input video format, there's already an issue open (#118) regarding this, please follow this for further discussion.
