### ISSUE TITLE
Unable to save video with Android 11

### ISSUE THREAD

**Issue by bmnidhin** [sbis04/video_trimmer#134]
The package is working perfectly perfectly in almost all devices except android 11. Is android 11 unsupported?

![WhatsApp Image 2021-09-10 at 4 33 32 PM](https://user-images.githubusercontent.com/11921692/132844939-93d116ba-56ba-4b42-beb9-e213bb84d9f5.jpeg)
![WhatsApp Image 2021-09-10 at 4 33 55 PM](https://user-images.githubusercontent.com/11921692/132844952-6bb29271-764b-4bbf-8335-3fff204cea0e.jpeg)
![WhatsApp Image 2021-09-10 at 4 34 11 PM](https://user-images.githubusercontent.com/11921692/132844966-d6fdad6c-bbd5-43df-b99e-3d217ca865d5.jpeg)

**Comment by sbis04** [comment]
@bmnidhin yes, it supports Android 11 perfectly, even the Android test device that I use is Pixel 4a (Android 11).

Can you please share your `flutter doctor -v` output? Also, let me know on which device you are facing this issue.

I have just released a new version of the `video_trimmer` plugin (v0.6.0), please try once with it and let me know.

**Comment by bmnidhin** [comment]
I used a samsung M12. IWe used an older version. Thanks
