### ISSUE TITLE
video_trimmer 0.4.0 depends on video_thumbnail ^0.3.3

### ISSUE THREAD

**Issue by ComradePashka** [sbis04/video_trimmer#135]
video_thumbnail v0.3.3 use a deprecated version of the Android embedding. This Android V2 embedding is mentioned at https://flutter.dev/go/android-plugin-migration and it was fixed in latest package update (at least in version 0.4.3, but your package still has dependency on that older version.
it is not directly related, but would be nice if you update pubspec.yaml accordingly.
thank you!

**Comment by sbis04** [comment]
I have updated all the dependencies now in `video_trimmer` version 0.6.0
