### ISSUE TITLE
The debug and release mode apk size skyrockets to almost 180MB and 85MB respectively. I don't seem to understand the issue here. Even checked my build.gradle. Flutter doctor is also perfectly fine.

### ISSUE THREAD

**Issue by utk28rsh** [sbis04/video_trimmer#139]

**Comment by sbis04** [comment]
In version `1.0.0` of this package, it by default uses the LTS version of FFmpeg which should reduce the overall app size.

**Comment by utk28rsh** [comment]
Sir, your update hasn't still fixed the issue. I mean just by importing the plugin in a flutter it increases the apk size by 7-8 times.
Please look into it.

**Comment by huzaifasaeed** [comment]
Any updates, regarding app size issue?

**Comment by utk28rsh** [comment]
No solution was found for fixing the app size issue. Apparently, no one seems to be discussing it because this issue makes this plugin unusable.

**Comment by sbis04** [comment]
Closing this issue for now, because there have been some changes to the `ffmpeg_kit_flutter`. Please open a new issue if you want to discuss it even further.

**Comment by sunilsinghchaudhary00** [comment]
apk size is so0 high did you fixed it or not
