### ISSUE TITLE
Is this plugin supports m3u8 format?

### ISSUE THREAD

**Issue by Hwan-seok** [sbis04/video_trimmer#140]
If it doesn't, how can I implement it?

**Comment by sbis04** [comment]
I'm not sure, FFmpeg seems to support this format but most probably you'll need to convert it to something like `mp4` (https://stackoverflow.com/questions/32528595/ffmpeg-mp4-from-http-live-streaming-m3u8-file) to use the video with this package.

**Comment by sbis04** [comment]
Closing this issue. Feel free to open if you want to discuss more about it.
