### ISSUE TITLE
API Level 24 is too large

### ISSUE THREAD

**Issue by prakash-sonar-98** [sbis04/video_trimmer#143]
How can I reduce android API level(24) of these package, It can affect my other dependencies

**Comment by shilangyu** [comment]
Just use the lts version of ffmpeg (set it in android/build.gradle)

```gradle
ext.flutterFFmpegPackage = 'full-lts'
```

**Comment by sbis04** [comment]
There is a breaking change in version `1.0.0` of this package, the `flutter_ffmpeg` package is being migrated to `ffmpeg_kit_flutter` (more info [here](https://github.com/tanersener/flutter-ffmpeg/issues/345)). Now, the configurations are also simpler and this package by default uses the LTS version of FFmpeg.

I'm closing this issue, feel free to reopen if you face any issues with the latest version.

**Comment by shilangyu** [comment]
Beware however that `ffmpeg_kit_flutter` currently has a API restriction bug: https://github.com/tanersener/ffmpeg-kit/issues/224#issuecomment-981054316

**Comment by sbis04** [comment]
@shilangyu Yes, I'm aware of that. If you check the Readme, I have added a **Troubleshooting** guide for that.
