### ISSUE TITLE
Long vides are not loading on the editor 

### ISSUE THREAD

**Issue by RohanSengupta326** [sbis04/video_trimmer#144]
Small length videos are getting loaded on the editing panel but videos which are a bit long they are not getting loaded. 
example :

https://user-images.githubusercontent.com/64458868/138545061-822cc31b-7bb8-4d8a-9fc4-8fd990f54683.mp4

**Comment by sbis04** [comment]
This is not actually due to the video length, it's because of the input video format. There's already an issue regarding this issue (#118), please follow this for further discussion.
