### ISSUE TITLE
ffmpegCommand does not support -crl or -preset

### ISSUE THREAD

**Issue by xmany** [sbis04/video_trimmer#147]
I can have custom ffmpeg command like this:
```
'-vf "scale=640:-1"'
```

but if I add:
```
'-vf "scale=640:-1" -crl 18 -preset slow'
```
Both options are not recognised, the process will fail.
How to use those options? Thanks!!

**Comment by sbis04** [comment]
Can you please what error are you exactly getting, and also please share the entire method `saveTrimmerVideo()` method how you have implemented it?

**Comment by sbis04** [comment]
Didn't get any reply. Assuming it to be solved, feel free to open it again if the issue still persists.
