### ISSUE TITLE
Cannot save file on custom path 

### ISSUE THREAD

**Issue by walikhan226** [sbis04/video_trimmer#150]
StorageDir.externalStorageDirectory is selected, i want to give a custom storage directory, because trimmed videos are not showing up in gallery

**Comment by walikhan226** [comment]
Need a way to save file on a custom local directory on android device

**Comment by sbis04** [comment]
you can use [gallery_saver](https://pub.dev/packages/gallery_saver) plugin to save the trimmed video to gallery

**Comment by walikhan226** [comment]
I don't think this package solves the problem, saveTrimmedVideo function does not return anything and automatically decides the saving location.

**Comment by ah89** [comment]
I have the same problem .saveTrimmedVideo used to return Future<string> but after upgrade Future<void> but in the code samples in the official page of the package you trained in old fashion:

_trimmer
        .saveTrimmedVideo(startValue: _startValue, endValue: _endValue)
        .then((value) {
      setState(() {
        _progressVisibility = false;
        _value = value;
      });
    });

`value` is void!

**Comment by sbis04** [comment]
@ah89 you can get the output path like this:

```dart
_trimmer.saveTrimmedVideo(
  startValue: _startValue,
  endValue: _endValue,
  onSave: (outputPath) {
    print('OUTPUT PATH: $outputPath');
  },
);
```

Check the example for more information.
