### ISSUE TITLE
Issue with video trimmer working code. Working code stopped working

### ISSUE THREAD

**Issue by aditya-mahajan96** [sbis04/video_trimmer#152]
My working code of video trimmer stopped working and showing error . It was working fine earlier. Below is the screenshot of what it appears now. It was working all fine earlier. @sbis04 @themadmrj @domliang @ArjanAswal 

<img width="1193" alt="Screenshot 2022-01-01 at 10 31 42 PM" src="https://user-images.githubusercontent.com/84502466/147864239-291b4ada-e475-49bf-8865-a8d9b765de68.png">

and here is the pubspec for **videos** i have 

> video_trimmer: ^1.0.0
>  ffmpeg_kit_flutter: ^4.5.0-LTS
> video_player: ^2.2.10
>  video_editor: ^1.2.2

If i add 
ffmpeg_kit_flutter:
    git:
      url: https://github.com/shilangyu/ffmpeg-kit
      ref: development-flutter
      path: prebuilt/bundle-flutter-lts/default

Then error comes. - 
**Because myproject depends on video_trimmer ^1.0.0 which depends on ffmpeg_kit_flutter 4.5.0-LTS, ffmpeg_kit_flutter from hosted is required.**

and if version is downgraded then

then  its showing error on save 
```
 _trimmer.saveTrimmedVideo(
      startValue: _startValue,
      endValue: _endValue,
      onSave: 
```
<img width="690" alt="Screenshot 2022-01-02 at 9 14 28 AM" src="https://user-images.githubusercontent.com/84502466/147865548-7d576df2-c350-47d8-9706-259b0c2daa09.png">

**Comment by sbis04** [comment]
@aditya-mahajan96 when is the error occurring exactly, during saving the trimmed video? Is the video trimmer preview getting generated (the thumbnails)?

**Comment by aditya-mahajan96** [comment]
During the saving the trimmed video method i am getting errror  . Yes i am getting the thumbnails of video trimmer.

**Comment by sbis04** [comment]
Okay, firebase notifications shouldn't cause any issues I believe.

I'll look into the issue and try to reproduce it, by today.

**Comment by akshayrupareliya0912** [comment]
Have you completed crop, trim using videoeditor package?

**Comment by iamjithinjohnson** [comment]
is this issue fixed?

**Comment by iamjithinjohnson** [comment]
i solved this issue with migrating package manually into our project.

**Comment by sbis04** [comment]
Sorry for the late fix. Have updated the package to use the latest version of `ffmpeg_kit_flutter` (4.5.1-LTS), this should fix this issue.
