### ISSUE TITLE
Update to ffmpeg_kit_flutter version 4.5.1

### ISSUE THREAD

**Issue by dev-zhang** [sbis04/video_trimmer#154]
There was a serious issue in ffmpeg_kit_flutter 4.5.0 which has been fixed in 4.5.1. Hope the author can update to ffmpeg_kit_flutter 4.5.1 as soon as possible. Thanks.
Related issue:
Flutter : FirebaseMessaging "onBackgroundMessage" with FFmpegKit #209
issue[#209](https://github.com/tanersener/ffmpeg-kit/issues/209)

**Comment by AhmedTarek-E** [comment]
I have the same issue and it is supposed to be fixed in the latest version of ffmpeg_kit_flutter.
Waiting for the update

**Comment by AhmedTarek-E** [comment]
I forked the repo and fixed the issue, you can use my fork until the main library is updated

https://github.com/AhmedTarek-E/video_trimmer

**Comment by sbis04** [comment]
Sorry for the late fix, had been quite busy with some other work. Have updated the package to use the latest version of `ffmpeg_kit_flutter` (4.5.1-LTS).
