### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses'. 

### ISSUE THREAD

**Issue by dannycortesv** [sbis04/video_trimmer#158]
Hi i'm using also ffmpeg_kit_flutter_full_gpl: ^4.5.1-LTS this cause duplicate classes failure. How can we change the package of ffmpeg plugins?

What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
Duplicate class com.arthenica.ffmpegkit.Abi found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.AbiDetect found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.AbstractSession found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.AsyncFFmpegExecuteTask found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.AsyncFFprobeExecuteTask found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.AsyncGetMediaInformationTask found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.BuildConfig found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.CameraSupport found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Chapter found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegKit found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$1 found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$2 found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$SAFProtocolUrl found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegSession found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFmpegSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFprobeKit found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFprobeSession found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.FFprobeSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Level found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Log found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.LogCallback found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.LogRedirectionStrategy found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.MediaInformation found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.MediaInformationJsonParser found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.MediaInformationSession found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.MediaInformationSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.NativeLoader found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Packages found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.ReturnCode found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Session found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.SessionState found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Signal found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.Statistics found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.StatisticsCallback found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)
Duplicate class com.arthenica.ffmpegkit.StreamInformation found in modules jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-full-gpl:4.5.1-1) and jetified-ffmpeg-kit-https-4.5.1-1-runtime (com.arthenica:ffmpeg-kit-https:4.5.1-1.LTS)

**Comment by felipeemidio** [comment]
Any update?

**Comment by dannycortesv** [comment]
@felipeemidio Make sure to use the same ffmpeg package on all puglins you use

**Comment by wolfwithflames** [comment]
Please help on this facing same issue.

**Comment by sbis04** [comment]
In your `pubspec.yaml` file, are you guys using both the `ffmpeg_kit_flutter` and the `video_trimmer` packages?

**Comment by felipeemidio** [comment]
Yes, @sbis04. My case is that I want to use the `video_trimmer` package **and**  the `ffmpeg_kit_flutter_https_gpl` for video convertion (both on version _4.5.1-LTS_).

**Comment by sbis04** [comment]
I'm not totally sure how this duplicate class error can be fixed, but this thread may help: https://stackoverflow.com/questions/56029393/why-im-getting-duplicate-class-when-running-my-android-project

**Comment by YofarDev** [comment]
For me the same problem of duplicate classes comes from using both ffmpeg_kit_flutter_min_gpl and video_trimmer (you can reproduce the problem by adding these 2 packages in a new project) and I don't get what I need to exclude in build.gradle?

**Comment by sbis04** [comment]
Closing this issue. Please open a new issue if you want to discuss this further.
