### ISSUE TITLE
FFmpeg processing failed, Couldn't save the video

### ISSUE THREAD

**Issue by eduardocontiero** [sbis04/video_trimmer#159]
Hi, I have this messages in my terminal :
FFmpeg processing failed
Couldn't save the video

and I also have this error then
Audio sink error
E/MediaCodecAudioRenderer(14541):   com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException:

**Comment by sbis04** [comment]
Are you testing on a physical device or an emulator? Can you please attach the `flutter doctor` output as well?

**Comment by sbis04** [comment]
Haven't received any user reply

**Comment by sbis04** [comment]
Haven't received any user reply
