### ISSUE TITLE
Because every version of flutter_test from sdk depends on path 1.8.0 and video_trimmer >=1.1.0 depends on path ^1.8.1, flutter_test from sdk is incompatible with video_trimmer >=1.1.0. So, because 'my app name 'depends on both video_trimmer ^1.1.1 and flutter_test from sdk, version solving failed. pub get failed (1; So, because  'my app name depends on both video_trimmer ^1.1.1 and flutter_test from sdk, version solving failed.)

### ISSUE THREAD

**Issue by jack84156** [sbis04/video_trimmer#160]
Because every version of flutter_test from sdk depends on path 1.8.0 and video_trimmer >=1.1.0 depends on path ^1.8.1, flutter_test from sdk is incompatible with video_trimmer >=1.1.0.
So, because  'my app name depends on both video_trimmer ^1.1.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because 'my app name 'depends on both video_trimmer ^1.1.1 and flutter_test from sdk, version solving failed.)

**Comment by trieuniemit** [comment]
Same problem. Please fix it.

**Comment by er-aman-gupta** [comment]
any one able to fix this??

**Comment by netharuM** [comment]
try downgrading the package 
I had the same issue with video_thumbnail (^0.5.0)
and I downgraded it to 0.4.6
that fixed the issue 
but I guess developers have to upgrade their dependencies in order to fix it

**Comment by netharuM** [comment]
I created a fork of this package 
and I'm maintaining dependencies there

**Comment by dundadevelop** [comment]
Hi, temporary add this to pubsec.yaml:
```
dependency_overrides: 
  path: ^1.8.1 
```

**Comment by sbis04** [comment]
This seems like `flutter_test` is not using the latest version of the `path` package (with version `1.8.1`) so that's causing this issue.

Will change the `path` to version `1.8.0` till the `flutter_test` updates

**Comment by sbis04** [comment]
Have updated the package, try out:

```yaml
video_trimmer: ^1.1.3
```
