### ISSUE TITLE
ThumbnailViewer renders thumbnails very slow.

### ISSUE THREAD

**Issue by er-aman-gupta** [sbis04/video_trimmer#161]
Hey there, the thumbnail viewer being used in TrimEditor renders thumbnails very slowly. Is there a way to speed it up or maybe show a loader while the thumbnails are being loaded.

Trying out the code from example project attached with the project.

**Comment by sbis04** [comment]
Yeah, it actually depends on how long is the video and also on the video resolution because thumbnails are generated at equal intervals of the video. For now, there's no way to show a loader (because the empty space signifies that the thumbnails are being loaded).

**Comment by er-aman-gupta** [comment]
I see. Would be a nice add on if you expose callback methods to indicate when loading starts/stops.

**Comment by sbis04** [comment]
The next version (`video_trimmer 2.0.0`) will have `onThumbnailLoadingComplete` callback.
