### ISSUE TITLE
Error when build with Firebase 

### ISSUE THREAD

**Issue by Velkamhell97** [sbis04/video_trimmer#165]
Hi friend, i want to use the package but I have not been able due to some problems when making the build:

1.  The first problem was with the minimum version of the sdk, which should be 24, this is easily solved by changing the minimum version in android/app/build.gradle

```
defaultConfig {
    // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
    applicationId "com.example.chat_app"
    minSdkVersion 24
    targetSdkVersion flutter.targetSdkVersion
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
}
```
2.  The second error has the following message: **_"More than one file was found with OS independent path 'lib/arm64-v8a/libavutil.so'. If you are using jniLibs and CMake IMPORTED targets, see  https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake"_**. Searching the internet, in StackOverflow someone publish the following solution: add the following line in android/app/build.gradle

```
android {
    // ...
    packagingOptions {
        pickFirst '**/*.so'
    }
}
```

With the line above the error message no longer appeared.

3.  The third error is the main reason for this issue, when I add the line in point 2, and I am using firebase services (firebase_core and others), the app builds successfully but the following error appears as soon as it tries to start the app: **_"MissingPluginException (MissingPluginException (No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core))"_**

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  runApp(const MyApp());
}
```

I don't know if the video_trimmer package is the cause of this error or the line added in point 2, I would be grateful if you could give me an idea of ​​what is happening and how I could solve it since I need to use firebase services.

Thanks!

**Comment by sbis04** [comment]
This is related to `firebase_core` package, please open an issue there if you are facing this.
