### ISSUE TITLE
having error running for iOS

### ISSUE THREAD

**Issue by wanoghoco** [sbis04/video_trimmer#167]
[!] CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter/https":
  In Podfile:
    ffmpeg_kit_flutter (from `.symlinks/plugins/ffmpeg_kit_flutter/ios`) was resolved to 4.5.1, which depends on
      ffmpeg_kit_flutter/https (= 4.5.1)

Specs satisfying the `ffmpeg_kit_flutter/https (= 4.5.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by ParhaMDeF** [comment]
Use these commands to install **ffmpeg_kit_flutter** correctly.
don't forget to put minimum ios support to version 10.0.
in my case, I put 14.0.
```
flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
flutter pub get
cd ios
pod install 
arch -x86_64 pod install  //(On an M1 mac use => arch -x86_64 pod install)
cd ..
flutter build ios
flutter run
```

**Comment by sbis04** [comment]
Are you still facing this issue?
