### ISSUE TITLE
Video Trim issue from gallery pick

### ISSUE THREAD

**Issue by expertdev-designer** [sbis04/video_trimmer#170]
When picking a video from gallery . Video Compress show file FileSystemException  cannot Retrieve length of file path. 

Video Path is coming fine.

While when  loading a video from camera its working fine.

void _loadVideo() async {
    print("widget.file.path ${widget.file}");
    _trimmer.loadVideo(videoFile: widget.file);
  }
![Simulator Screen Shot - iPhone 13 - 2022-07-20 at 10 03 33](https://user-images.githubusercontent.com/52417551/179897667-6acdf7d0-d60a-4cd7-990c-94b397d3115d.png)

**Comment by Jatin141** [comment]
Hello Team Any update same issue happen in my device also and i checked other device it is working fine. Thanks
![simulator_screenshot_AD77895D-8F5A-466B-ACEC-EE31191290B1](https://user-images.githubusercontent.com/106056823/195105299-a62291cd-7df0-4d91-b7b0-97d2d63dfeec.png)

**Comment by sbis04** [comment]
@expertdev-designer are you facing this issue while using `video_compress`?

@Jatin141 are you facing this issue with all videos? And, which device are you using?

**Comment by Jatin141** [comment]
@sbis04 some video have face this issue.

**Comment by sbis04** [comment]
Upon some investigation, I noticed that some videos which are not directly present on the device (selected either from Google Photos or iOS Photos stored on iCloud) are having this issue.

@Jatin141 are the videos present on the device or being fetched from cloud storage as stated earlier?

**Comment by Jatin141** [comment]
@sbis04 this issue is happen for fetched video in device gallery for andorid and ios both. but issue is generate some video not the all video. thanks

**Comment by sbis04** [comment]
Okay, then it might be video specific issue (and that can occur for various reasons). @Jatin141 is it possible to share a video with me that's having this issue?

**Comment by ChristineWasike** [comment]
Currently still facing this same issue. The video is on device but still loads as above
