### ISSUE TITLE
could i control the trimmer slider? like could i set the start and the end of the slider using this package?

### ISSUE THREAD

**Issue by khaledmurtaja** [sbis04/video_trimmer#172]
i do not  want the trimming slider to take the video(Start and end) , i want to customize  it  using specific time interval ? it is possible using this package ?

**Comment by vugn** [comment]
Same prob, did u already get it?

**Comment by sbis04** [comment]
No, currently it's not possible using this package to limit the total duration of the video. But you can try using the `ffmpeg_kit_flutter` package to trim the video to a particular length before sending it to the video trimmer.

**Comment by khaledmurtaja** [comment]
I have added some edits to the package, so it can suits my use case(one of them was about specfiying start time for the slider).
I do not think that i should make a pull request for my edits cuz its so customized for my use case.
Good work from you!
