### ISSUE TITLE
Maintenance 

### ISSUE THREAD

**Issue by Helocominc** [sbis04/video_trimmer#175]
Is this plug-in still maintained? 

There are lots of PR and issues that has not been responded to. Kindly update the status of this package. 
@sbis04

**Comment by sbis04** [comment]
Yes, it is still maintained. A new version is coming soon with some nice updates fixing a lot of issues that were open for a long time! 🙏

**Comment by Helocominc** [comment]
Thank you a lot for the maintenance. I really like this package and making use of it.
