### ISSUE TITLE
 could not access /data/user/0/com.example.app/app_flutter/Trimmer/file.mp4

### ISSUE THREAD

**Issue by ParhaMDeF** [sbis04/video_trimmer#176]
i tried to compress the trimmed video by **video_compress** package but I gets an error.
 

> Unexpected error while transcoding.
> E/TranscodeEngine(32461): java.lang.IllegalArgumentException: could not access /data/user/0/com.example.app/app_flutter/Trimmer/image_picker9113914114815938940_trimmed:Sep20,2022-14:59:48.mp4
> E/TranscodeEngine(32461): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:370)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.source.UriDataSource.initializeRetriever(UriDataSource.java:33)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.source.DefaultDataSource.initialize(DefaultDataSource.java:57)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.DataSources.init(DataSources.kt:22)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.DataSources.init(DataSources.kt:26)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.DataSources.<init>(DataSources.kt:35)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.DataSources.<init>(DataSources.kt:17)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:33)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
> E/TranscodeEngine(32461): 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
> E/TranscodeEngine(32461): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
> E/TranscodeEngine(32461): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
> E/TranscodeEngine(32461): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
> E/TranscodeEngine(32461): 	at java.lang.Thread.run(Thread.java:1012)

**Comment by nazrulahmed-bs** [comment]
Is there any update about this issue?

**Comment by sbis04** [comment]
Seems like it's an issue only on Android emulator as per the discussion [here](https://github.com/jonataslaw/VideoCompress/issues/83). It's always recommended to use the `video_trimmer` package on a physical device.

Did you try it on any physical device?
