### ISSUE TITLE
FfmpegkitFlutterPlugin error 

### ISSUE THREAD

**Issue by Helocominc** [sbis04/video_trimmer#178]

**Comment by sbis04** [comment]
Can you please provide a bit more description of the error?

**Comment by Helocominc** [comment]
When I set the trimmer video max length to 1l30 seconds the slider won't move. The start slider only move from 00 and stop in end slider which is 30secs of the video length.  

Expected behavior:
Allow the trimmer slider to move when maxVideoLength is set but get only 30secs of the video clip.

**Comment by sbis04** [comment]
I didn't totally understand your question. But when the `maxVideoLength` is set to 30 seconds, you should be able to select a maximum of 30 seconds from the video (if the total length of the video is less than 30 seconds then the `maxVideoLength` would default to the length of the video).

**Comment by Helocominc** [comment]
If I set the `maxVideoLength` to 30secs it only get the videos 30secs (from 00 to 30secs) and doesn't move to select other part of the video. It just get stuck on the first 00 to 30secs.

**Comment by sbis04** [comment]
Oh, that's weird -- is it possible for you to share with me a screen capture of it? And, also the actual total length of that video file.

**Comment by Helocominc** [comment]
This is a sample video of the bug. The slider doesn't move on drag to other video length. 

Uploading Screen_Recording_20221029-161013.mp4…

**Comment by sbis04** [comment]
Got it, it's actually because the center portion is almost fully covered by the holder tap sizes, so it might be very hard to move the slider (otherwise it should have been possible to drag by holding inside the selected area). The next update should solve this because it supports a scrollable trimmer area!

**Comment by UtsavShrestha101** [comment]
Any development on it?
