### ISSUE TITLE
Left and right trimmer slider activate at once 

### ISSUE THREAD

**Issue by Helocominc** [sbis04/video_trimmer#179]
When the left slider is focused the right slider too become active and causes the left slider not to move. Same thing happens the other way round. 
Below is a sample video of the issue 

https://user-images.githubusercontent.com/90664424/197882041-30759af7-8469-4836-8f41-0a372d59c4fb.mp4

Expected Behavior:
The slider that is tapped should move not the one that is not tapped. 
Sample below 

https://user-images.githubusercontent.com/90664424/197882708-76a76946-b9bb-495e-bb9f-61d9b04b5b07.mp4

**Comment by sbis04** [comment]
The bug with the trimmer holders will be solved in the next update (`video_trimmer 2.0.0`).

**Comment by Helocominc** [comment]
That will be great. Will constantly keep checking for new updates
