### ISSUE TITLE
FFmpeg processing failed when using storageDir: StorageDir.applicationDocumentsDirectory

### ISSUE THREAD

**Issue by lnbs97** [sbis04/video_trimmer#183]
Hey, I am getting these errors when I try to save a video with storageDir parameter set to "StorageDir.applicationDocumentsDirectory":

`I/flutter (15317): FFmpeg process exited with state COMPLETED and rc 1`
`I/flutter (15317): FFmpeg processing failed.`
`I/flutter (15317): Couldn't save the video`

Documentation says that "StorageDir.applicationDocumentsDirectory" should be the default value, so how can this cause an error?

**Comment by sbis04** [comment]
This doesn't seem like an issue with the saving, but rather an issue with the FFmpeg trimming. Did you try out with any other videos?

It has been seen earlier that if a video is selected from Google Photos or other cloud storage medium (and is not present on the device), it causes an issue in the FFmpeg processing (maybe you can download the video on device and then select it inside the app to understand if that's the issue).
