### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter/https":

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [sbis04/video_trimmer#185]
I got this error when pod install:

[!] CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter/https":
  In Podfile:
    ffmpeg_kit_flutter (from `.symlinks/plugins/ffmpeg_kit_flutter/ios`) was resolved to 5.1.0, which depends on
      ffmpeg_kit_flutter/https (= 5.1.0)

Specs satisfying the `ffmpeg_kit_flutter/https (= 5.1.0)` dependency were found, but they required a higher minimum deployment target.

//platform :ios, '11.0'
//Flutter version :3.3.7

**Comment by sbis04** [comment]
Did you try out [this troubleshooting step](https://github.com/sbis04/video_trimmer#troubleshooting)?

**Comment by JmyW** [comment]
@sbis04 Hi, I got same failure. And I did check the troubleshooting step but not helpful. 

Any idea how to fix it?

**Comment by adiiisanjayaa** [comment]
any update?
