### ISSUE TITLE
Usage without ffmpeg

### ISSUE THREAD

**Issue by szotp-lc** [sbis04/video_trimmer#191]
This is a nice library, but ffmpeg is a huge dependency. It would be nice if saveTrimmedVideo was provided as a separate package, so that we could use video_trimmer as a UI, and then generate on our own.

In my use case (gif), it may be enough to generate a bunch of thumbnails and join them using image package, but for someone else, they could trim the video on backend, or maybe even use [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm).

**Comment by sbis04** [comment]
Nice idea! But currently there's no plan to separate the UI.
