### ISSUE TITLE
Error creating release iOS

### ISSUE THREAD

**Issue by furthurr** [sbis04/video_trimmer#2]
Hi bro. i can use my app on simulator and my device ios and android. but ...  i have this error when i try to create a release

`flutter build ios --release`

> Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_MobileFFprobe", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_ArchDetect", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
    ld: symbol(s) not found for architecture armv7
> 
Imagen:

![errores](https://user-images.githubusercontent.com/639790/81040535-2fa4ce80-8e71-11ea-94f6-95004cea7be7.png)

Mis configuraciones: 

![configurations](https://user-images.githubusercontent.com/639790/81040106-35e67b00-8e70-11ea-988d-4dd50790e292.png)
 
Xcode try run archive: 

![xcode](https://user-images.githubusercontent.com/639790/81040639-6844a800-8e71-11ea-834b-0a52cd9cee77.png)

Thank you!!!!

**Comment by sbis04** [comment]
Hi, take a look at this thread for a probable fix: https://github.com/tanersener/flutter-ffmpeg/issues/109

**Comment by sbis04** [comment]
Closing this issue. @furthurr you can open if you face any further problem.
