### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Abhay-cloud** [sbis04/video_trimmer#208]
![image](https://github.com/sbis04/video_trimmer/assets/54390973/8e8ff4ba-498b-468d-88ab-5d925395580e)
![image](https://github.com/sbis04/video_trimmer/assets/54390973/dcaf685e-fc9a-4602-bef4-905bd529404c)

**Comment by Rafik-Belkadi-malou** [comment]
you must provide `onChangePlaybackState` to the TrimViewer

**Comment by Abhay-cloud** [comment]
Yes, I already provided onChangePlaybackState. @Rafik-Belkadi-malou

**Comment by andynvt** [comment]
same issue on iOS

**Comment by sbis04** [comment]
Should be fixed in the latest version `4.0.0`!
