### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by shinytruth** [sbis04/video_trimmer#222]
Thank you for making a great plugin.

I have one question. It seems to use FFMPEG internally, but this source is under the MIT license. As far as I know, the FFMPEG source follows the LGPL license and this license is contagious. Is this source free from there?

**Comment by shinytruth** [comment]
Even if I create an app with this plugin and upload it to the store, isn't there an obligation to disclose the source code of my app?

**Comment by shinytruth** [comment]
@sbis04 Please take a look!

**Comment by sbis04** [comment]
Sorry, had been busy with work, and didn't have a chance to look into any comments.

Thank you for your feedback! The plugin doesn't include or redistribute FFmpeg directly; it relies on system-installed libraries or external dependencies. We ensure compliance with MIT and respect all dependencies' licenses.
