### ISSUE TITLE
Minimum Android version

### ISSUE THREAD

**Issue by wilfredonoyola** [sbis04/video_trimmer#25]
Thanks for this great package, it will be very useful for the new trends related to Videos.

I would like to know why the minimum version of Android is 24?

I suppose it has to do with the FFmpeg package that requires a minimum version of android.

Do you have a future plan to cover more versions until at least 23?

I see that at level 23 is 16.9% of the devices with this version.

I leave here the reference.

![distribution android version](https://user-images.githubusercontent.com/1428168/84388322-9d9b8e80-abb1-11ea-9a31-fe79ced2b965.PNG)

**Comment by braysonjohn148** [comment]
i think he is using Ffmpeg which does require 24  and above, This comment should be seen by Ffmpeg also, as they can fix it.

**Comment by wilfredonoyola** [comment]
Of course @braysonjohn148 , But i have seen it. I do not sure if will work with api levels below of 24

![release](https://user-images.githubusercontent.com/1428168/84528760-7e7a2b00-ac9d-11ea-865b-7097ae1b53cb.PNG)


Reference: https://github.com/tanersener/flutter-ffmpeg#23-lts-releases

**Comment by braysonjohn148** [comment]
great!!!... i also changed mine to 24. Thanks now i have to change back to 16

**Comment by braysonjohn148** [comment]
What if you the same package but instead of using 
`ext.flutterFFmpegPackage = 'full'`
as he instructed(that allow 24 and above),
You use `ext.flutterFFmpegPackage = 'full-its'` as the FFmpeg says(that allows 16 and above).

_did not test it yet, just thinking._

**Comment by sbis04** [comment]
Sorry for the confusion. I have updated the Readme regarding this package version.

**Comment by AxesandGrinds** [comment]
Your instructions are not clear enough. Do I need to create a local package of flutter_ffmpeg in order to change to ext.flutterFFmpegPackage = 'full-its'? Because when I add ext.flutterFFmpegPackage = 'full-its' to the build gradle file, it still gives me the error that minimum api is 24. Please, create more precise instructions or release an alternative package with the LTS configuration already put in place.

**Comment by wilfredonoyola** [comment]
@AxesandGrinds Could you check this example for [code line](https://github.com/sbis04/video_trimmer/blob/master/example/android/build.gradle#L29)?

**Comment by AxesandGrinds** [comment]
I added that, it's still giving me the same error:

```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] C:\Sparks\Flutter\sparks_im\build\flutter_ffmpeg\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by AxesandGrinds** [comment]
I fixed the issue by adding to pubspec.yaml

```
flutter_ffmpeg:
    git:
      url: git://github.com/tanersener/flutter-ffmpeg.git
      ref: v0.2.1
      path: packages/flutter_ffmpeg_full_lts
```

I'm not sure why it was still picking up the non-lts package even though I had made a video_trimmer a local dependency an added that code ^ there as well. But adding it to my main pubspec.yaml file fixed the issue.
