### ISSUE TITLE
incompatible with flutter_localizations

### ISSUE THREAD

**Issue by PitiGo** [sbis04/video_trimmer#3]
I get this message when using this library with flutter_localizations.

"Because every version of flutter_localizations from sdk depends on intl 0.16.0 and every version of video_trimmer depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with video_trimmer."

I tried downgrading but didn't work.

**Comment by sbis04** [comment]
You can fix this by overriding the **intl** dependency. Just add the following line to your `pubspec.yaml` file:

```yaml
dependency_overrides:
  intl: ^0.16.0
```

**Comment by PitiGo** [comment]
thanks!! that worked.
