### ISSUE TITLE
Thumbnail images of video is not showing correctly?

### ISSUE THREAD

**Issue by ubaidsuhail** [sbis04/video_trimmer#30]
Hi,When I open videos the thumbnail images that come bottom are not loading correctly?Once the thumbnail loaded and suddenlt they skipped?
Error:This an error shown below:
               "getFrameAtTime: videoFrame is a NULL pointer"

**Comment by sbis04** [comment]
Hey @ubaidsuhail, please send me your `flutter doctor` result. Also, is this issue occurring in the example app as well?

**Comment by tinnit1** [comment]
Hello, I have this problem when starting the video, even with the test project, any ideas.
![DFD2699B-0263-46C9-A87B-1958EE562235](https://user-images.githubusercontent.com/45150540/88357345-8e6f3b00-cd30-11ea-9d14-59dfd04c4688.PNG)

**Comment by tinnit1** [comment]
Hello, I have this problem when starting the video, even with the test project, any ideas.
![A9E5AA8A-D0C9-4CDE-B68A-C7EA6AB5A11C](https://user-images.githubusercontent.com/45150540/88357419-cd9d8c00-cd30-11ea-81b6-a75282f48b61.JPG)

**Comment by sbis04** [comment]
@tinnit1 I didn’t quite understand the issue you are facing. Can you please share more details?

**Comment by tinnit1** [comment]
the problem is that apparently when the image is longer than it is wide, fill in the missing with black spaces, I think that could be it, since with square videos I don't have that problem, this is a 4: 3 or 16: 9 video

**Comment by sbis04** [comment]
Yeah, it is because for each thumbnail image it is set to `BoxFit.fitHeight` and the size of the thumbnail image is square. So, it fills up the remaining space with black bars.

Thanks for reporting this. I will try to define one more property for `TrimEditor` which will let you specify the image **fit** type of each thumbnail image.

**Comment by ubaidsuhail** [comment]
You can also use Boxfit.fill to cover the remaining space

**Comment by sbis04** [comment]
Added a new property called `fit` to `TrimEditor` widget which will let you specify the image **fit** type of each thumbnail image.

Refer to: 30f6015afcc33dbd2586d07718f9c8f0a33ab5ef
