### ISSUE TITLE
Trimming videos less than 1sec

### ISSUE THREAD

**Issue by Mangielijah** [sbis04/video_trimmer#31]
The is an issue with trimming videos less than 1 second  (any time less than 0:00:00 which can be 0:00:00.30), the trimmed video cannot be played

**Comment by sbis04** [comment]
Hey @Mangielijah, there is an issue of video frames freeing towards the start and end positions, for fixing this the FFmpeg trimmed video length was set to **seconds**. Refer: #22 

But, as it is not fixing that issue I have reverted it to **milliseconds** in `v0.2.5`.  So, this issue should be fixed now.
