### ISSUE TITLE
startValue and endValue is in seconds, milliseconds, or microseconds?

### ISSUE THREAD

**Issue by AxesandGrinds** [sbis04/video_trimmer#33]
Your readme and api code does not say what time the startValue and endValue is measured in. Is it measured in seconds, milliseconds, or microseconds? Please clarify this and update readme.

**Comment by braysonjohn148** [comment]
i also want to set a certain video length. How can i do so.

**Comment by AbhayVAshokan** [comment]
Yes. How can we set the video length to like 30 seconds max? To implement the same, I need to know what the ```startValue``` and ```endValue``` mean. Does it represent milliseconds or seconds?

**Comment by braysonjohn148** [comment]
i think its miliseconds. I tried but i fails. I tried to check if(){} on the onchange but i can stop the scroller from moving

**Comment by sbis04** [comment]
Hey @AxesandGrinds, the `startValue` & `endValue` is currently measured in **milliseconds** in `v0.2.5`. I have also updated the **API Docs** for this.

**Comment by sbis04** [comment]
@AbhayVAshokan @braysonjohn148 currently the package does not let you specify any maximum trimmed video length. I am currently working on this issue, you can track it here: #4
