### ISSUE TITLE
Profile Mode Error

### ISSUE THREAD

**Issue by Mangielijah** [sbis04/video_trimmer#37]
This plugin works perfectly for me when i am in debug mode, but in profile mode the is an error, widgets do not display, just a blank grey screen

**### Debug Mode**
![WhatsApp Image 2020-07-23 at 12 46 17 PM](https://user-images.githubusercontent.com/15947050/88283442-470e8d80-cce3-11ea-99bd-f61e753eabc1.jpeg)

**### Profile Mode**
![WhatsApp Image 2020-07-23 at 12 49 55 PM](https://user-images.githubusercontent.com/15947050/88283512-6ad1d380-cce3-11ea-8a66-2455c24f81c2.jpeg)

Profile modes of an app depicts the release mode perfomance, just wondering if this issue will be in the app when released

**Comment by sbis04** [comment]
Hey @Mangielijah, I have tested the package on **debug**, **profile**, and **release** modes and it is working fine in all of them.

Are you getting any errors on the console while running on the device in profile mode?

**Comment by Mangielijah** [comment]
Launching lib\main.dart on Pixel 3 XL in profile mode...
√ Built build\app\outputs\apk\profile\app-profile.apk (64.2MB).
Connecting to VM Service at ws://127.0.0.1:6522/3g7TICJj24w=/ws
I/flutter (25548): we got the data + Instance of '_MapStream<QuerySnapshotPlatform, QuerySnapshot>' this is name  mangi
I/example.chatap(25548): Waiting for a blocking GC ProfileSaver
I/BiChannelGoogleApi(25548): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@444e74
W/DynamiteModule(25548): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(25548): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(25548): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/example.chatap(25548): The ClassLoaderContext is a special shared library.
I/example.chatap(25548): The ClassLoaderContext is a special shared library.
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->copyMemory(JJJ)V (greylist, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getByte(J)B (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getByte(Ljava/lang/Object;J)B (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getLong(J)J (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->putByte(JB)V (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->putByte(Ljava/lang/Object;JB)V (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/example.chatap(25548): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
I/example.chatap(25548): The ClassLoaderContext is a special shared library.
W/example.chatap(25548): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
V/NativeCrypto(25548): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
W/example.chatap(25548): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
D/NetworkSecurityConfig(25548): No Network Security Config specified, using platform default
I/ProviderInstaller(25548): Installed default security provider GmsCore_OpenSSL
W/example.chatap(25548): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/example.chatap(25548): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
W/example.chatap(25548): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/example.chatap(25548): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/example.chatap(25548): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
I/BiChannelGoogleApi(25548): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@444e74
D/FirebaseAuth(25548): Notifying id token listeners about user ( QcJxkUczBON6uFKSzQSps2Exnd13 ).
D/FirebaseAuth(25548): Notifying id token listeners about user ( QcJxkUczBON6uFKSzQSps2Exnd13 ).
W/Firestore(25548): (21.3.0) [FirestoreCallCredentials]: Failed to get token: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.
I/flutter (25548): Loading flutter-ffmpeg.
I/mobile-ffmpeg(25548): Loading mobile-ffmpeg.
I/flutter (25548): ══╡  ╞══════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25548): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25548): Path Init: dir.path
I/mobile-ffmpeg(25548): Loaded mobile-ffmpeg-min-gpl-arm64-v8a-4.3.1-lts-20200125.
D/mobile-ffmpeg(25548): Callback thread started.
I/flutter (25548): Loaded flutter-ffmpeg-android-arm64-v8a.
I/flutter (25548): Another exception was thrown: Instance of 'ErrorSummary'
I/example.chatap(25548): Waiting for a blocking GC ProfileSaver
I/flutter (25548): false
I/example.chatap(25548): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 15.167ms
I/flutter (25548): showAttachment: true
I/flutter (25548): false
D/FilePickerDelegate(25548): Selected type video/*
I/FilePickerDelegate(25548): [SingleFilePick] File URI:content://com.android.providers.media.documents/document/video%3A3720
E/FilePickerUtils(25548): Getting for API 19 or abovecontent://com.android.providers.media.documents/document/video%3A3720
E/FilePickerUtils(25548): Document URI
E/FilePickerUtils(25548): Media Document URI
I/FilePickerUtils(25548): Video Media Document URI
I/FilePickerDelegate(25548): Absolute file path:/storage/emulated/0/WhatsApp/Media/WhatsApp Animated Gifs/VID-20200719-WA0024.mp4
I/flutter (25548): /storage/emulated/0/WhatsApp/Media/WhatsApp Animated Gifs/VID-20200719-WA0024.mp4
I/flutter (25548): /data/user/0/com.example.chatapp/cache/VID-20200719-WA0024.mp4
W/example.chatap(25548): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(25548): Init 5c2b987 [ExoPlayerLib/2.9.6] [crosshatch, Pixel 3 XL, Google, 29]
D/CCodec  (25548): allocate(c2.qti.avc.decoder)
I/Codec2Client(25548): Available Codec2 services: "default" "software"
I/Codec2Client(25548): Creating a Codec2 client to service "default"
I/Codec2Client(25548): Client to Codec2 service "default" created
I/CCodec  (25548): setting up 'default' as default (vendor) store
I/Codec2Client(25548): Creating a Codec2 client to service "default"
I/Codec2Client(25548): Client to Codec2 service "default" created
I/CCodec  (25548): Created component [c2.qti.avc.decoder]
D/CCodecConfig(25548): read media type: video/avc
D/ReflectedParamUpdater(25548): extent() != 1 for single value type: output.buffers.pool-ids.values
D/CCodecConfig(25548): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig(25548): ignoring local param raw.color (0xd2001809) as it is already supported
D/CCodecConfig(25548): ignoring local param raw.hdr-static-info (0xd200180a) as it is already supported
I/CCodecConfig(25548): query failed after returning 17 values (BAD_INDEX)
D/CCodecConfig(25548): c2 config diff is Dict {
D/CCodecConfig(25548):   c2::i32 algo.priority.value = -1
D/CCodecConfig(25548):   c2::float algo.rate.value = 4.2039e-44
D/CCodecConfig(25548):   c2::u32 algo.secure-mode.value = 0
D/CCodecConfig(25548):   c2::float coded.frame-rate.value = 30
D/CCodecConfig(25548):   c2::u32 coded.pl.level = 20480
D/CCodecConfig(25548):   c2::u32 coded.pl.profile = 20480
D/CCodecConfig(25548):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig(25548):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig(25548):   c2::u32 coded.vui.color.range = 0
D/CCodecConfig(25548):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig(25548):   c2::u32 default.color.matrix = 0
D/CCodecConfig(25548):   c2::u32 default.color.primaries = 3
D/CCodecConfig(25548):   c2::u32 default.color.range = 2
D/CCodecConfig(25548):   c2::u32 default.color.transfer = 0
D/CCodecConfig(25548):   c2::u32 input.buffers.max-size.value = 13271040
D/CCodecConfig(25548):   c2::u32 input.delay.value = 4
D/CCodecConfig(25548):   string input.media-type.value = "video/avc"
D/CCodecConfig(25548):   c2::u32 output.delay.value = 18
D/CCodecConfig(25548):   string output.media-type.value = "video/raw"
D/CCodecConfig(25548):   c2::u32 raw.color.matrix = 0
D/CCodecConfig(25548):   c2::u32 raw.color.primaries = 0
D/CCodecConfig(25548):   c2::u32 raw.color.range = 0
D/CCodecConfig(25548):   c2::u32 raw.color.transfer = 0
D/CCodecConfig(25548):   c2::float raw.hdr-static-info.mastering.blue.x = 1.4013e-45
D/CCodecConfig(25548):   c2::float raw.hdr-static-info.mastering.blue.y = 1.4013e-45
D/CCodecConfig(25548):   c2::float raw.hdr-
W/ColorUtils(25548): expected specified color aspects (0:0:0:0)
D/SurfaceUtils(25548): connecting to surface 0x73635d4010, reason connectToSurface
I/MediaCodec(25548): [c2.qti.avc.decoder] setting surface generation to 26161153
D/SurfaceUtils(25548): disconnecting from surface 0x73635d4010, reason connectToSurface(reconnect)
D/SurfaceUtils(25548): connecting to surface 0x73635d4010, reason connectToSurface(reconnect)
D/CCodecConfig(25548): no c2 equivalents for csd-1
D/CCodecConfig(25548): no c2 equivalents for native-window
D/CCodecConfig(25548): c2 config diff is   c2::i32 algo.priority.value = 0
D/CCodecConfig(25548):   c2::u32 input.buffers.max-size.value = 393216
D/CCodecConfig(25548):   c2::u32 raw.max-size.height = 480
D/CCodecConfig(25548):   c2::u32 raw.max-size.width = 480
D/CCodecConfig(25548):   c2::u32 raw.pixel-format.value = 34
D/CCodecConfig(25548):   c2::u32 raw.size.height = 480
D/CCodecConfig(25548):   c2::u32 raw.size.width = 480
W/Codec2Client(25548): query -- param skipped: index = 1107298332.
D/CCodec  (25548): client requested max input size 21946, which is smaller than what component recommended (393216); overriding with component recommendation.
W/CCodec  (25548): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (25548): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (25548):   int32_t feature-secure-playback = 0
D/CCodec  (25548):   int32_t frame-rate = 30
D/CCodec  (25548):   int32_t height = 480
D/CCodec  (25548):   int32_t level = 1
D/CCodec  (25548):   int32_t max-input-size = 393216
D/CCodec  (25548):   string mime = "video/avc"
D/CCodec  (25548):   int32_t priority = 0
D/CCodec  (25548):   int32_t profile = 1
D/CCodec  (25548):   int32_t width = 480
D/CCodec  (25548):   Rect crop(0, 0, 479, 479)
D/CCodec  (25548): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (25548):   int32_t android._video-scaling = 1
D/CCodec  (25548):   Rect crop(0, 0, 479, 479)
D/CCodec  (25548):   int32_t color-standard = 4
D/CCodec  (25548):   int32_t color-range = 2
D/CCodec  (25548):   int32_t color-transfer = 3
D/CCodec  (25548):   int32_t android._dataspace = 259
D/CCodec  (25548):   int32_t width = 480
D/CCodec  (25548):   int32_t feature-secure-playback = 0
D/CCodec  (25548):   int32_t frame-rate = 30
D/CCodec  (25548):   int32_t height = 480
D/CCodec  (25548):   int32_t max-height = 480
D/CCodec  (25548):   int32_t max-width = 480
D/CCodec  (25548):   string mime = "video/raw"
D/CCodec  (25548):   int32_t priority = 0
D/CCodec  (25548):   int32_t rotation-degrees = 0
D/CCodec  (25548):   Buffer hdr-static-info = {
D/CCodec  (25548):     00000000:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
D/CCodec  (25548):     00000010:  00 00 00 00 00 00 00 00  00                       .........
D/CCodec  (25548):   }
D/CCodec  (25548):   int32_t android._color-format = 21307083
W/Codec2Client(25548): query -- param skipped: index = 1342179345.
W/Codec2Client(25548): query -- param skipped: index = 2415921170.
W/Codec2Client(25548): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Query input allocators returned 0 params => BAD_INDEX (6)
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Query output allocators returned 0 params => BAD_INDEX (6)
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Query output surface allocator returned 0 params => BAD_INDEX (6)
I/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Created output block pool with allocatorID 18 => poolID 2003 - OK
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] Configured output block pool ids 2003 => OK
D/Codec2-block_helper(25548): remote graphic buffer migration 0/0
D/Codec2Client(25548): generation remote change 26161153
W/Gralloc3(25548): allocator 3.x is not supported
E/ion     (25548): ioctl c0044901 failed with code -1: Invalid argument
D/CCodecConfig(25548): c2 config diff is   c2::u32 raw.color.primaries = 3
D/CCodecConfig(25548):   c2::u32 raw.color.range = 2
D/CCodecConfig(25548):   c2::u32 raw.crop.height = 480
D/CCodecConfig(25548):   c2::u32 raw.crop.left = 0
D/CCodecConfig(25548):   c2::u32 raw.crop.top = 0
D/CCodecConfig(25548):   c2::u32 raw.crop.width = 480
D/CCodecBufferChannel(25548): [c2.qti.avc.decoder#515] onWorkDone: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBufferChannel(25548):   int32_t android._video-scaling = 1
D/CCodecBufferChannel(25548):   Rect crop(0, 0, 479, 479)
D/CCodecBufferChannel(25548):   int32_t color-standard = 2
D/CCodecBufferChannel(25548):   int32_t color-range = 2
D/CCodecBufferChannel(25548):   int32_t color-transfer = 3
D/CCodecBufferChannel(25548):   int32_t android._dataspace = 258
D/CCodecBufferChannel(25548):   int32_t width = 480
D/CCodecBufferChannel(25548):   int32_t feature-secure-playback = 0
D/CCodecBufferChannel(25548):   int32_t frame-rate = 30
D/CCodecBufferChannel(25548):   int32_t height = 480
D/CCodecBufferChannel(25548):   int32_t max-height = 480
D/CCodecBufferChannel(25548):   int32_t max-width = 480
D/CCodecBufferChannel(25548):   string mime = "video/raw"
D/CCodecBufferChannel(25548):   int32_t priority = 0
D/CCodecBufferChannel(25548):   int32_t rotation-degrees = 0
D/CCodecBufferChannel(25548):   Buffer hdr-static-info = {
D/CCodecBufferChannel(25548):     00000000:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
D/CCodecBufferChannel(25548):     00000010:  00 00 00 00 00 00 00 00  00                       .........
D/CCodecBufferChannel(25548):   }
D/CCodecBufferChannel(25548):   int32_t android._color-format = 2130708361
D/CCodecBufferChannel(25548):   int32_t color-format = 2130708361
D/CCodecBufferChannel(25548): }
I/flutter (25548): Another exception was thrown: Instance of 'ErrorSummary'
I/chatty  (25548): uid=10261(com.example.chatapp) 1.ui identical 1 line
I/flutter (25548): Another exception was thrown: Instance of 'ErrorSummary'

**Comment by sbis04** [comment]
Most probably "gray screen" is an indication of error in the **release** mode, similar to the "red error screen" in **debug** mode.

Refer to this issue: https://github.com/flutter/flutter/issues/53482

**Comment by sbis04** [comment]
**Closing this issue**, as it is not related to this plugin.
