### ISSUE TITLE
Please help me.Output path have no metadata

### ISSUE THREAD

**Issue by Yaungku** [sbis04/video_trimmer#38]

**Comment by sbis04** [comment]
Hi @Yaungku, can you please provide more details about the issue you are facing?

**Comment by Yaungku** [comment]
the problem is solved now. mp4 audio cannot be encoded with "-c:a copy". So, ffmepg don't work and create nothing. So , there is no file in the path. Instead of using "-c:a copy", I use "-c:a aac" to encode mp4 audio and it work.

**Comment by Yaungku** [comment]
Thank for the reply bro
