### ISSUE TITLE
Not able to specify a maximum output video length

### ISSUE THREAD

**Issue by JamesBondPc** [sbis04/video_trimmer#4]
I want make this , this app is VN on App store , How to make this UI ?

**Comment by sbis04** [comment]
You can use **CustomPaint** widget and **GestureDetector** for creating this UI. I have a similar implementation in my package, you can take inspiration from that. You can also use my package and make modifications in that to achieve this UI, as this is quite similar to it.

**Comment by JamesBondPc** [comment]
Hi , I set&nbsp;viewerWidth  in  
TrimEditor

but I can't edit 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Souvik Biswas"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 下午4:05
收件人: "sbis04/video_trimmer"<video_trimmer@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sbis04/video_trimmer] hi, I want make this  (#4)





 
You can use CustomPaint widget and GestureDetector for creating this UI. I have a similar implementation in my package, you can take inspiration from that. You can also use my package and make modifications in that to achieve this UI, as this is quite similar to it.

**Comment by sbis04** [comment]
Currently, the package does not allow you to specify a maximum output video length. I already have this functionality in the list for an upcoming improvement and working on it.

**Comment by AxesandGrinds** [comment]
Please, is there any update on this? It's been almost 2 months, we need this feature.

**Comment by AxesandGrinds** [comment]
> Currently, the package does not allow you to specify a maximum output video length. I already have this functionality in the list for an upcoming improvement and working on it.

If there isn't a limit for maximum output video length then this package isn't useful for most people trying to trim videos especially for an instant messaging app wherein videos have to be trimmed to predetermined maximum. I don't think this is an incredibly hard feature to role out.  I'm looking at the trim_editor.dart where the code has to be written, but I don't have knowledge of how _endPos and _videoEndPos should be updated when _setVideoStartPosition is called. Can you take an hour to add this functionality?

**Comment by wilfredonoyola** [comment]
Hey @AxesandGrinds, you could try fix it and send a PR. ?

**Comment by AxesandGrinds** [comment]
@wilfredonoyola , I'm not able to fix it. I don't understand the Offset and deltas from DragUpdateDetails enough to make the change. Sorry.

**Comment by wilfredonoyola** [comment]
OK @AxesandGrinds , We are waiting by @sbis04

**Comment by sbis04** [comment]
Sorry for not releasing this feature for so long. As I was busy with some other projects, I wasn't getting much time to work on this. Though I had started working on this feature, it's not ready to be released and some work is left.

Please wait for some more time @AxesandGrinds @wilfredonoyola @JamesBondPc

**Comment by braysonjohn148** [comment]
Any new update.

**Comment by braysonjohn148** [comment]
hello. any updates

**Comment by sbis04** [comment]
**Finally, the most awaited feature is here! (v0.2.7)**  🎉

Sorry for this huge delay.

I have added a new property called `maxVideoLength` for specifying the **max length** of the output video.

Refer: 53ddb9f0c63b8312f0cf10fa19d64beee4a4552a
