### ISSUE TITLE
Why Isn't API Level higher than 16 And less than 24 Supported

### ISSUE THREAD

**Issue by RalphMarvin** [sbis04/video_trimmer#41]
I have an App that is using lots of libraries and plugins that targets API level 21 but i cant get your plugin to work with it.

**Comment by sbis04** [comment]
Hi @RalphMarvin, the package is tested on `minSdkVersion 21` as well. 

Which **FFmpeg** package name are you using from [this list](https://pub.dev/packages/video_trimmer#packages-list)?

If you are using it on **16 < API < 24**, then `LTS Release` is only supported.

**Comment by RalphMarvin** [comment]
I used 'full-lts' FFmpeg package name

**Comment by sbis04** [comment]
Can you please share a screenshot of the error?

**Comment by RalphMarvin** [comment]
Hi there, I seemed to have done something wrong. It builds successfully
now. Thanks for your help. I'll close the issue now.
