### ISSUE TITLE
Multiple VideoViewer is same page

### ISSUE THREAD

**Issue by denniswhchung** [sbis04/video_trimmer#42]
Can I use multiple VideoViewer and Trimmer in same page?
I have more than one video loaded with PageView.builder
I tried couple ways to develop but failed.

Looking forward to your advice.

**Comment by sbis04** [comment]
Though I have not yet tried this, I believe there would be an issue with the multiple controllers and it would also be very memory hungry.

One suggestion is, you can load multiple videos on the page but keep one Trimmer. Then switch between videos to show the Timmer accordingly.

If you can provide more info on your implementation, I may help better.
