### ISSUE TITLE
Move whole slider

### ISSUE THREAD

**Issue by kameshkarthi** [sbis04/video_trimmer#43]
Hello sir, Please add the functionality to move the whole slider, when the maximum duration is reached.

**Comment by PhantomRay** [comment]
check this out: https://github.com/huangred/video_trimmer/commits/master

Still buggy, but has the feature you want.

**Comment by PhantomRay** [comment]
In my own implementation, I can move the whole video instead of slider.

  <img src="https://github.com/huangred/video_trimmer/raw/master/screenshots/editor_demo.gif" alt="Trim Editor" />

**Comment by kameshkarthi** [comment]
Good work bro!!! Thanks...

**Comment by maxsap** [comment]
> In my own implementation, I can move the whole video instead of slider.
> 
> ![Trim Editor](https://github.com/huangred/video_trimmer/raw/master/screenshots/editor_demo.gif)

wouldn't it make sense to open it as a PR to this one as well?

**Comment by PhantomRay** [comment]
> > In my own implementation, I can move the whole video instead of slider.
> > ![Trim Editor](https://github.com/huangred/video_trimmer/raw/master/screenshots/editor_demo.gif)
> 
> wouldn't it make sense to open it as a PR to this one as well?

This is a very different approach as how to trim video from UX perspective. Plus I have other requirements. So I have to create my own repo.

**Comment by ArjanAswal** [comment]
@sbis04 Can you please provide a rough timeline for the implementation of this feature? When can we expect it?

**Comment by carman247** [comment]
Will this eventually be added to the original package?

**Comment by themadmrj** [comment]
> check this out: https://github.com/huangred/video_trimmer
> 
> Still buggy, but has the feature you want.

@PhantomRay do you plan on merging new commits? Your features look good, but the repo is 50 commits behind...

**Comment by sbis04** [comment]
Fixed in PR #109
