### ISSUE TITLE
Video not saving

### ISSUE THREAD

**Issue by chinu999** [sbis04/video_trimmer#44]
some times video save at android/data/com.trimmer.videotrimmer/files/Picture/(video saved here)

but some times it did not save at that place

and where can i find this location
/data/user/0/com.trimmer.videotrimmer/app_flutter/Trimmer/image_picker6447870776611015947_trimmed:Aug14,2020-08:25:17.mp4 
i did not get it any where in my phone

**Comment by sbis04** [comment]
Did you use the default storage option of the package or anything other like `StorageDir.externalStorageDirectory`?

**Comment by chinu999** [comment]
Thanks for replying I figure out the problem what is going on here . Actually in build.gridle file I target to sdk 29 but when I target to sdk 28 everything works fine.

**Comment by SonamKamble** [comment]
@sbis04 I used default storage option , also target sdk is 28. Still getting the same issue as above. Kindly guide me..
