### ISSUE TITLE
Having Issues On iOS Platform 10.0

### ISSUE THREAD

**Issue by RalphMarvin** [sbis04/video_trimmer#45]
Facing build issues on iOS platform 10.0, am using the 'full-lts' package.
I get the ff error:

```
Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_MobileFFprobe", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      "_OBJC_CLASS_$_ArchDetect", referenced from:
          objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
```

**Comment by sbis04** [comment]
Do check this issue: https://github.com/tanersener/flutter-ffmpeg/issues/36
Also this StackOverflow thread: https://stackoverflow.com/questions/6429494/undefined-symbols-for-architecture-armv7

But first of all, try this:
* Run the following from the root folder:
  
  ```bash
  flutter clean
  ```
* Then, from the `ios` folder run:
  
  ```bash
  pod install
  ```

* Now, try running the app again.

**Comment by RalphMarvin** [comment]
> Do check this issue: [tanersener/flutter-ffmpeg#36](https://github.com/tanersener/flutter-ffmpeg/issues/36)
> Also this StackOverflow thread: https://stackoverflow.com/questions/6429494/undefined-symbols-for-architecture-armv7
> 
> But first of all, try this:
> 
> * Run the following from the root folder:
>   ```shell
>   flutter clean
>   ```
> * Then, from the `ios` folder run:
>   ```shell
>   pod install
>   ```
> * Now, try running the app again.

None of the solutions from the above links worked. Still facing the same issue

**Comment by sbis04** [comment]
Okay, I now understand. It is actually happening due to the implementation of [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg). Unfortunately `Flutter v1.20.x` changed the `Podfile` format. It will soon be fixed by the creator of **flutter_ffmpeg** package.

Refer to this issue: https://github.com/tanersener/flutter-ffmpeg/issues/175
