### ISSUE TITLE
video pass

### ISSUE THREAD

**Issue by chinu999** [sbis04/video_trimmer#47]
when ever i try to pass a video to other class it says

The getter 'path' was called on null.
Receiver: null
Tried calling: path

i tried this code:

 ```
    RaisedButton(
                  onPressed: _progressVisibility
                      ? null
                      : () async {
                    _saveVideo().then((outputPath) async{
                      Navigator.push(
                          context, MaterialPageRoute(
                          builder: (context) => Edit(
                            videoPath: outputPath,
                          )));
                      print('OUTPUT PATH: $outputPath');
                      final snackBar = SnackBar(
                        content: Text('Video Saved successfully $outputPath'),
                      );
                      Scaffold.of(context).showSnackBar(snackBar);
                    });
//                    checkTime();
                  },
                  child: Text("SAVE"),
                ),
```

is there any way i can save video in my dir something like this:

```
 final Directory extDir = await getApplicationDocumentsDirectory();

    final String dirPath = '${extDir.path}/videos';
    await Directory(dirPath).create(recursive: true);
    String videoFileName = '${timestamp()}.mp4';

    String videoFile = '$dirPath/${timestamp()}.mp4';
```

**Comment by sbis04** [comment]
You can specify the storage directory by specifying the property `storageDir` in the `saveTrimmedVideo()` method. Also, you can specify the `videoFileName` and `videoFolderName` property to give a custom name to them.

Are you getting the output video path, when you print it?

```dart
print('OUTPUT PATH: $outputPath');
```

If you want to load the video from the output path on your `Edit` page, you can use the following code:

```dart
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    if (outputVideoPath != null) {
      _controller = VideoPlayerController.file(File(outputVideoPath))
        ..initialize().then((_) {
          setState(() {});
        });
    }
  }
```

**Comment by VrushabhDesai3** [comment]
> You can specify the storage directory by specifying the property `storageDir` in the `saveTrimmedVideo()` method. Also, you can specify the `videoFileName` and `videoFolderName` property to give a custom name to them.
> 
> Are you getting the output video path, when you print it?
> 
> ```dart
> print('OUTPUT PATH: $outputPath');
> ```
> 
> If you want to load the video from the output path on your `Edit` page, you can use the following code:
> 
> ```dart
>   VideoPlayerController _controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     if (outputVideoPath != null) {
>       _controller = VideoPlayerController.file(File(outputVideoPath))
>         ..initialize().then((_) {
>           setState(() {});
>         });
>     }
>   }
> ```

Can you please explain in detail with example?

**Comment by sbis04** [comment]
I have included an example now.
