### ISSUE TITLE
TrimEditor Unable to zoom

### ISSUE THREAD

**Issue by JamesBondPc** [sbis04/video_trimmer#48]
GestureDetector(
                    onScaleUpdate: (ScaleUpdateDetails details) {
                      print("scale ");
                      setState(() {
                       
                        if( details.scale.clamp(.8, 10.0) == 1) 
                          {
                            return;
                          }
                        _width = 200 * details.scale.clamp(.8, 10.0);
                      });
                      print("scale width "+ _width.toString());
                    },
                    onScaleEnd: (ScaleEndDetails details) {
                      setState(() {
                      
                      });
                    },
                    child:  
                      TrimEditor(

**Comment by sbis04** [comment]
Closing this as it is similar to this issue: #52
