### ISSUE TITLE
iOS force to compress video

### ISSUE THREAD

**Issue by PhantomRay** [sbis04/video_trimmer#50]
Hi there,
In iOS, once a video is selected, the video is compressed before going to trim interface, while this step is skipped in Android.

Any hint to remove this behaviour in iOS? It causes the video being proccessed (compressed) twice resulting bad quality.

**Comment by sbis04** [comment]
I am not familiar with this. Does it really compress the video?

Can you please provide me more information on this issue @PhantomRay ?

**Comment by PhantomRay** [comment]
I found out that it's more of an iOS specific behavior when using file picker plugin.

**Comment by sbis04** [comment]
Yeah, I am not sure if it can be prevented and as I am using the file picker plugin in this package there is that similar behavior.

**Comment by sbis04** [comment]
Closing this, as it is not directly related to this package.
