### ISSUE TITLE
On iOS, VideoViewer can not be sought to certain seconds by VideoPlayerController

### ISSUE THREAD

**Issue by Creolophus** [sbis04/video_trimmer#58]
Thanks for your gorgeous package!

Please check the GIF below, 

![seek_issue](https://user-images.githubusercontent.com/7787790/96566539-442e3380-12f8-11eb-816e-8c7b20799b53.gif)

**Comment by qbait** [comment]
Are you planning to implement it @sbis04 ?
It would improve the UX by far.
Also, refreshing `VideoViewer` when dragging the start and stop in `TrimEditor` (on Android and iOS) would be a great addition?

**Comment by qbait** [comment]
Are you planning to implement it @sbis04 ?
It would improve the UX by far.
Also, refreshing VideoViewer when dragging the start and stop in TrimEditor (on Android and iOS) would be a great addition.

**Comment by sbis04** [comment]
@Creolophus I think what you meant is the TrimEditor widget. Yes, currently dragging the endpoint beyond the defined maximum limit, doesn't update the start position. So, you have to drag the start position, and then again you will be able to drag the end position.

Yes @qbait, I will be implementing this soon.

There is already an issue regarding this, so I am closing this. Refer: #43
