### ISSUE TITLE
ffmpg error in your pods

### ISSUE THREAD

**Issue by mohyM** [sbis04/video_trimmer#65]
[!] CocoaPods could not find compatible versions for pod "flutter_ffmpeg/https":
  In Podfile:
    flutter_ffmpeg (from `.symlinks/plugins/flutter_ffmpeg/ios`) was resolved to 0.3.0, which depends on
      flutter_ffmpeg/https (= 0.3.0)

Specs satisfying the `flutter_ffmpeg/https (= 0.3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by sbis04** [comment]
I think your issue got solved, according to this conversation: https://github.com/tanersener/flutter-ffmpeg/issues/225

**Comment by sbis04** [comment]
Closing this issue, as it is solved [here](https://github.com/tanersener/flutter-ffmpeg/issues/225).
