### ISSUE TITLE
Support for latest video_player plugin

### ISSUE THREAD

**Issue by dannycortesv** [sbis04/video_trimmer#67]
I can't update video_player plugin to 1.0.0 due that video_trimmer doesn't support it, will be great to add support :D Thanks for your amazing work mate!

**Comment by RalphMarvin** [comment]
This is very important. I need this as well.

**Comment by sbis04** [comment]
I have updated the plugin versions to the latest ones.

**Comment by dannycortesv** [comment]
This is great, thank you Souvik!!!
