### ISSUE TITLE
Load list of video files

### ISSUE THREAD

**Issue by kameshkarthi** [sbis04/video_trimmer#7]
Hello sir, How can i load list of video files??
Good Job!!!

**Comment by sbis04** [comment]
I didn't quite understand your question. Why do you want to load multiple video files for trimming?

Do you want to trim multiple files at the same time? I don't think it is a good decision to do that.

If you still want to achieve that kind of functionality, then you can try to use this package or modify it as per your need.

**Comment by kameshkarthi** [comment]
if i want share videos after trimming like whats app, then how can i do that??

**Comment by sbis04** [comment]
You can access the file by its **path** and then you can perform any operation upon it.

**Comment by kameshkarthi** [comment]
I did it by passing the video file in trimmer.loadvideo() function instead of selecting from gallery..
Thank you so much sir....

**Comment by sbis04** [comment]
Great! Closing this as the issue is fixed.
