### ISSUE TITLE
when I load a video , flutter push me weird screen not trimmerScreen

### ISSUE THREAD

**Issue by yoonjiyong** [sbis04/video_trimmer#79]
okay Im trying my best to explain this.

i used to use this trimmer package very well 
but in iOS some weird situation happens 

1. I click gallery button 
![clickGallery](https://user-images.githubusercontent.com/68573852/103268952-e9037600-49f7-11eb-9366-5ad7c28b19d9.jpeg)

2. choose video from gallery 
![chooseVideo](https://user-images.githubusercontent.com/68573852/103268961-f882bf00-49f7-11eb-8fb3-a5d1e224cb02.jpeg)

3. **_Here comes weird screen_** 
I never make this one 
[ IOS ] - I don't know where it comes from 

![playingVideo](https://user-images.githubusercontent.com/68573852/103269009-2536d680-49f8-11eb-81d6-364e2a45d996.jpeg)

[ ANDROID ] - I expect this and made this screen 
![photo_2020-12-29 17 09 31](https://user-images.githubusercontent.com/68573852/103269269-d2a9ea00-49f8-11eb-9ee7-e1d8423f1383.jpeg)

4. if I choose select button it compresses 
![compressing](https://user-images.githubusercontent.com/68573852/103269049-48618600-49f8-11eb-9003-289221c935c5.jpeg)

5. after compressing is done, my phone  lost connection 

I have no idea what do i have to do. 

here's my code

DIALOG 
`final picker = ImagePicker();

  PickedFile file = await picker.getVideo(
    source: ImageSource.gallery,
  );

  if (file != null) {
    await _trimmer.loadVideo(videoFile: File(file.path));
    Navigator.of(context).push(MaterialPageRoute(builder: (context) {
      return TrimVideoScreen(trimmer: _trimmer);
    }));
  }`

Flutter doctor
`
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

don't know why Flutter , dart plugin warning , 
cuz it installed well 
`

**Comment by sbis04** [comment]
This is a known issue.
I have used the `image_picker` plugin in the example app of this package, it already has an issue open related to this: https://github.com/flutter/flutter/issues/24954

iOS does compression of some kind before letting you modify the selected video by default.

**Comment by sbis04** [comment]
I have updated the example app using `file_picker` package (instead of `image_picker`), which allows skipping the iOS video compression screen.

Check out the version `0.3.5`: #81

**Comment by yoonjiyong** [comment]
you rock 🤟
