### ISSUE TITLE
How to add subtitles under the picture

### ISSUE THREAD

**Issue by JamesBondPc** [sbis04/video_trimmer#8]
How to add subtitles under the picture

**Comment by sbis04** [comment]
If I have understood your question correctly, you want to add subtitles to the images inside the trim viewer. So, for that, you can use **Stack** and position the **Text** on top of each image.

**Comment by JamesBondPc** [comment]
I want to put it under the picture, and also want to make a timeline above the picture




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Souvik Biswas"<notifications@github.com&gt;; 
发送时间: 2020年5月13日(星期三) 下午3:18
收件人: "sbis04/video_trimmer"<video_trimmer@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sbis04/video_trimmer] How to add subtitles under the picture (#8)





 
If I have understood your question correctly, you want to add subtitles to the images inside the trim viewer. So, for that, you can use Stack and position the Text on top of each image.

**Comment by sbis04** [comment]
By the picture, are you referring to the video viewer? You can add the subtitle simply by adding a **Text** widget under the video viewer as all the UI components of the **video_trimmer** are separate implementations, so you can arrange them in whatever fashion you want.

For the timeline, you can basically use the **VideoEditor** widget, it is a kind of timeline.

**Comment by JamesBondPc** [comment]
like this






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Souvik Biswas"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 上午9:55
收件人: "sbis04/video_trimmer"<video_trimmer@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sbis04/video_trimmer] How to add subtitles under the picture (#8)





 
By the picture, are you referring to the video viewer? You can add the subtitle simply by adding a Text widget under the video viewer as all the UI components of the video_trimmer are separate implementations, so you can arrange them in whatever fashion you want.
 
For the timeline, you can basically use the VideoEditor widget, it is a kind of timeline.

**Comment by sbis04** [comment]
Do you have any other queries? Or you can just close this issue.

**Comment by JamesBondPc** [comment]
How to achieve the effect like the picture, add gesture swipe, use padding to control it seems to be not effective




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Souvik Biswas"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 上午10:05
收件人: "sbis04/video_trimmer"<video_trimmer@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sbis04/video_trimmer] How to add subtitles under the picture (#8)





 
Do you have any other queries? Or you can just close this issue.
