### ISSUE TITLE
Lost connection when I call _saveVideo() in iOS [^0.3.5]

### ISSUE THREAD

**Issue by yoonjiyong** [sbis04/video_trimmer#83]
I think you can understand with only codes so... 

### flutter doctor 
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale ko-KR) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
IPhone7

**-------------------------------------------------------------------------------------------**

### loading images from gallery with file picker 
         
            FilePickerResult result = await FilePicker.platform.pickFiles(
              type: FileType.video,
              allowCompression: false,
            );

            if (result != null) {
              File file = File(result.files.single.path);
              await _trimmer.loadVideo(videoFile: file);
              Navigator.of(context).push(
                MaterialPageRoute(builder: (context) {
                  return TrimVideoScreen(trimmer: _trimmer); ✅
                }),
              );

**-------------------------------------------------------------------------------------------**

### TrimVideoScreen ✅

`
            class TrimVideoScreen extends StatefulWidget {
              final Trimmer trimmer;
              TrimVideoScreen({this.trimmer});

              @override
              _TrimVideoScreenState createState() => _TrimVideoScreenState();
            }

            class _TrimVideoScreenState extends State<TrimVideoScreen> {
              double _startValue = 0.0;
              double _endValue = 0.0;

              bool _isPlaying = false;
              bool _progressVisibility = false;

              Future<String> _saveVideo() async {
                setState(() {
                  _progressVisibility = true;
                });
                print('Came here 😀');
                String _value;
                try {            
                  print('Came here2 😀');
                  await widget.trimmer ✅ Lost connection to device. in HERE ❌❌❌
                      .saveTrimmedVideo(startValue: _startValue, endValue: _endValue)
                      .then((value) {
                    setState(() {
                      _progressVisibility = false;
                      _value = value;
                    });
                  });
                } catch (e) {
                  print('Came here3 😀');
                }
            
                return _value;
              }
...

            SaveVideo Button onPressed {
                            
            await _saveVideo().then( ✅
              (outputPath) {
                print('OUTPUT PATH: $outputPath');
             },
            ).catchError((onError) {
              print('error is $onError');
            });
            }

`

**-------------------------------------------------------------------------------------------**

### LOG 

flutter: Came here 😀

flutter: Came here2 😀

flutter: DateTime: Jan 7, 2021 - 15:50:59

flutter: Formatted: Jan7,2021-15:50:59

flutter: 🔍︎ TrimVideo Builded

flutter: Exists

flutter: Retrieved Trimmer folder

flutter: Start: 0:00:00.000000 & End: 0:00:13.400000

flutter: /var/mobile/Containers/Data/Application/92D5B540-6CDF-49CE-85D6-5F29B573833E/Documents/Trimmer/

flutter: OUTPUT: .mp4

Lost connection to device.

**-------------------------------------------------------------------------------------------**

### PROCESS
1. load trimmer with FilePicker
2. go to TrimVideoScreen() 
3. after set start point , end point 
4. call _saveTrimmer to get trimmedUrl => ERROR OCCUS  

**-------------------------------------------------------------------------------------------**
I tried with TrimmerView Class 
its Same result 
when I click save Button it dies 
### LOG
flutter: DateTime: Jan 7, 2021 - 17:28:35
flutter: Formatted: Jan7,2021-17:28:35
flutter: Exists
flutter: Retrieved Trimmer folder
flutter: Start: 0:00:00.000000 & End: 0:00:13.400000
flutter: /var/mobile/Containers/Data/Application/7A2D57AF-E412-474F-A77D-0BFB5B167E74/Documents/Trimmer/
flutter: OUTPUT: .mp4
Lost connection to device.

Help! 😅

**Comment by sbis04** [comment]
@yoonjiyong  Can you please try with the latest version `0.4.0`, and let me know

**Comment by yoonjiyong** [comment]
this version works fine !

**Comment by braysonjohn148** [comment]
I am using version 0.4.0, ext.flutterFFmpegPackage = 'https-gpl-lts' but still crash when i press save

**Comment by sbis04** [comment]
@braysonjohn148 can you please the error you are getting in the console?

**Comment by sbis04** [comment]
Closing this issue

**Comment by JuniorFlorentino** [comment]
OUTPUT: .mp4
flutter: Loading ffmpeg-kit-flutter.
flutter: Loaded ffmpeg-kit-flutter-ios-https-x86_64-4.5.0-lts.
Lost connection to device.

**Comment by JuniorFlorentino** [comment]
versão 1.0.0 do package 

OUTPUT: .mp4
flutter: Loading ffmpeg-kit-flutter.
flutter: Loaded ffmpeg-kit-flutter-ios-https-x86_64-4.5.0-lts.
Lost connection to device.
