### ISSUE TITLE
take some time when I get video on gallery on iOS [ ^0.3.5 ] 

### ISSUE THREAD

**Issue by yoonjiyong** [sbis04/video_trimmer#84]
hello

when I load video on gallery with this code, 
recorded video takes some times.

--------------------------------------------------------------------------------
### flutter doctor 
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale ko-KR) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
IPhone7

### The codes
FilePickerResult result = await FilePicker.platform.pickFiles(
    type: FileType.video,
    allowCompression: false,
);

if (result != null) {
File file = File(result.files.single.path);
 _trimmer.loadVideo(videoFile: file);
Navigator.of(context).push(
MaterialPageRoute(builder: (context) {
return TrimVideoScreen(trimmer: _trimmer);
}),
);

--------------------------------------------------------------------------------

it's okay with downloaded video 
but it takes time recorded video. 
I mean , videos which I took.

downloaded videos = okay 
recorded videos = NOT okay 

it takes some times to go to TrimVideoScreen ,
I think its compressing or something 
cuz 
the time different with  videos length.
 
short video = short time
long video = long time

man i wish to good at english 
anyway i hope you to understand. 🙂

**Comment by sbis04** [comment]
Have you tried in a release build if you are facing the same delay? 

Also, are you using `allowCompression: false` which was introduced as a part of https://github.com/sbis04/video_trimmer/pull/81 ?

Please try with the latest package `0.4.0`, and let me know.

**Comment by yoonjiyong** [comment]
thanks but there is one problem 😭 
i'll write about it

**Comment by sbis04** [comment]
Closing this issue
