### ISSUE TITLE
Saved video doesn't seem to be the same as the previewed section

### ISSUE THREAD

**Issue by carman247** [sbis04/video_trimmer#85]
This is great but I think there is some difference between the trimmed preview and the actual saved file.

e.g. preview is from 00:15 - 00:25 seconds, saved file seems to be 00:10 - 00:30

This is even though the _start and _end seem to be correct

**Comment by alymbouras** [comment]
Same here, it's not 100% the same. It's a few milliseconds off.

**Comment by sbis04** [comment]
This difference is because a video can only be trimmer from a keyframe position, detailed explanation [here](https://stackoverflow.com/a/18449609). You can set `applyVideoEncoding: true` in the `saveTrimmedVideo()` method to solve this issue to some extent.
