### ISSUE TITLE
Any plan to add web or desktop support?

### ISSUE THREAD

**Issue by dannycortesv** [sbis04/video_trimmer#87]
Will be awesome if we can have this working on web or desktop

**Comment by sbis04** [comment]
This package can't support web and/or desktop platforms as it uses `flutter_ffmpeg` which can only be run on **Android** & **iOS** currently.

**Comment by ZaLiTHkA** [comment]
quick note on this front: not sure if it's worth opening a whole new issue for...

when I had a look at `flutter_ffmpeg`, I noticed a [`README` update](https://github.com/tanersener/flutter-ffmpeg/commit/fca32a79bc3ce7bb5fc76f5de0f5af5de9de3b61) from 7 months back to say:

> Not maintained anymore, superseded by [FFmpegKit](https://github.com/tanersener/ffmpeg-kit). See [FlutterFFmpeg to FFmpegKit Migration Guide](https://github.com/tanersener/ffmpeg-kit/wiki/Migrating-From-FlutterFFmpeg).

I then checked `ffmpeg-kit`, who's GitHib repo description states:

> FFmpeg Kit for applications. Supports Android, Flutter, iOS, macOS, React Native and tvOS. Supersedes MobileFFmpeg, flutter_ffmpeg and react-native-ffmpeg.

so, basically at least one _could_ add macOS support _here_ with making the change..

but then I had a look through the issue logs, searching specifically for requests for the other desktop platforms, and it seems Windows and Linux support isn't quite here yet..

it's worth keeping an eye on tanersener/ffmpeg-kit#8 and tanersener/ffmpeg-kit#3 though. (:
